language: android
env:
 global:
 - ANDROID_API=24
 - EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=24.0.2
 - ADB_INSTALL_TIMEOUT=5 # minutes
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API_LEVEL
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
    - sys-img-armeabi-v7a-android-21
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
jdk:
  - oraclejdk8
before_install:
- yes | sdkmanager "platforms;android-27"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
#  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
install:
  - sdkmanager --list || true # Debug / Observation
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2" #&> /dev/null
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2" #&> /dev/null
  - avdmanager --list || true  # Debug / Observation
script:
  - ./gradlew cleanAllModules
  - ./gradlew testAllModulesTravis
  - if [[ -n $TRAVIS_TAG ]]; then ./gradlew ship; fi
dist: precise
